### ISSUE TITLE
Change game music with keyboard shortcuts. 

### ISSUE THREAD

**Issue by sgosal2** [sgosal2/Afterdark#1]
Right now, all you can do in the game is turn the music on or off. I want to go in and be able to change the song. To start off, I would add a new song into the sounds folder in the media folder. In order to make this kind of change, I would have to alter multiple classes. The first would be the "MenuPane.java" file. The menu is the first thing that pops up when you click to launch the game. The music is automatic to the default. This change will need to go into Settings. A new section will be added to show the keyboard short cuts to change the song "M" will be for the default music. "N" will be the new key that will need to be added to create a shortcut to change the music to the other option of a song. A new keyPressed if statement will need to be added to "Settings.java" to account for this change. The same change will need to be also added to "PauseMenu.java", "MenuPane.java", and "Game.java". This will ensure that no matter where in the gameplay you are, whether it be in the startup menu, the actual game or the pause game menu, that you will be able to change the music from the default to the alternative at any time. "AudioPlayer.java" does not need to be altered by the looks of it because all it takes in are file and filenames for the parameters to actually play or stop the sounds. As long as the filename in the keys in the other files are correct, this should not be an issue. Another key should also be added to stop music all together. "B" key is the best key to perform the operation as of right now. It is right next to the "M" and "N" keys so it will be convenient for the user to keep them in the same area. No new classes will be needed, just a new audio file and changing of a few classes.

**Comment by onzfonz** [comment]
Implement this one.

**Comment by sgosal2** [comment]
Some things had to change from my original understanding of the code. There is no alternative music for the main menu, just the main menu music. The game's music itself is the one with the alternative. You have to be playing the game in order to switch up the music. Instead of adding instructions in the settings pane, they were added in the controls pane. 

M = Default game music
N = Alternative game music
B = Turn off all music
V = Turn sound on/off

**Main Menu:**
1. Press B to stop music
2. Press M to play music again
3. Click on Settings
4. Press M, B, or V and see the button highlights change.

**Game**
1. Press Play on the Main Menu (You will hear the default music once the game starts)
2. Press N to play the alternative music.
3. Press B to stop music
4. Press M or N to play either music options
5. Press Enter to shoot (Notice the sound effect of a gun firing)
6. Press V to turn off sound
7. Press Enter to shoot (Notice the sound effect is not being heard)
8. Press V to turn sound on
9. Press Enter to shoot (Notice the sound effect is there again)

**Pause Menu**
The pause menu will have similar features to the game so play around with turning on and off the music with the same commands listed at the top.
